import h5py

raw_dataset_path = "../robosuite/custom_dataset/demo.hdf5"
final_dataset_path = "../robosuite/custom_dataset/low_dim_button_lightbulb.hdf5"

f_raw = h5py.File(raw_dataset_path, "r")
f_final = h5py.File(final_dataset_path, "a")

for ep in f_final["data"]:
    ep_grp_final = f_final["data"][ep]
    ep_grp_raw = f_raw["data"][ep]
    
    # 1. Grab the ground-truth hidden states from the raw file
    if "custom_bulb_states" in ep_grp_raw:
        true_bulb_states = ep_grp_raw["custom_bulb_states"][:]
        true_target_idx = ep_grp_raw["custom_target_bulb_idx"][:]
    else:
        continue
        
    # 2. Grab the fake 53-D object array generated by Robomimic
    object_array = ep_grp_final["obs"]["object"][:]
    num_steps = object_array.shape[0]
    
    # --- NEW SAFETY CHECK ---
    if len(true_bulb_states) < num_steps:
        print(f"[!] Skipping {ep}: Custom data was truncated during collection ({len(true_bulb_states)} vs {num_steps} steps).")
        continue
    # ------------------------
    
    # Trim the true arrays to perfectly match the object array length (N+1 states -> N states)
    true_bulb_states = true_bulb_states[:num_steps]
    true_target_idx = true_target_idx[:num_steps]
    
    # 3. SURGICAL PATCH: Overwrite the fake columns with the true data
    object_array[:, 24:28] = true_bulb_states
    object_array[:, 28] = true_target_idx
    
    # 4. Delete the fake dataset and save the patched one back
    del ep_grp_final["obs"]["object"]
    ep_grp_final["obs"].create_dataset("object", data=object_array)
    
    print(f"[{ep}] Patched obs/object! Sliced to {num_steps} steps.")

f_raw.close()
f_final.close()
print("\n[✓] Ground-truth object states successfully injected!")